target-version = "py39"
line-length = 100
exclude = ["venv", ".venv", "__pycache__", ".ipynb_checkpoints", ".pytest_cache", "evaluate.py", "myfile.py"]

[lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[lint.per-file-ignores]
"main.py" = ["E402", "I001"]
